#include <bur/plctypes.h>

#ifdef _DEFAULT_INCLUDES
#include <AsDefault.h>
#endif

#include "ABB_Library.h"

// Custom Lib.: Base conversion between data.
#include "Converter.h"

void Sim_PROFINET_Mapping_IO_Data(struct ABB_Library* inst);

typedef enum Robot_State_ID_enum{
	ROB_STATE_ACTIVE,
	ROB_STATE_POWER,
	ROB_STATE_WAIT,
	ROB_STATE_UPD_PARAMETERS,
	ROB_STATE_MOTION_1,
	ROB_STATE_MOTION_2,
	ROB_STATE_HOME_UPD_PARAMETERS,
	ROB_STATE_HOME_MOTION_1,
	ROB_STATE_HOME_MOTION_2,
	ROB_STATE_STOP,
	ROB_STATE_SAFETY,
	ROB_STATE_ERROR
}Robot_State_ID_enum;

_LOCAL struct ABB_Library ABB_Library_Rob_1;

_LOCAL USINT Sim_PROFINET_Mapping_IN[256];
_LOCAL USINT Sim_PROFINET_Mapping_OUT[256];

void Sim_PROFINET_Mapping_IO_Data(struct ABB_Library* inst){
	// Mapping Input Data.
	inst->PROFINET_Mapping_IN.STATUS.INPUT = Sim_PROFINET_Mapping_IN[1];
	inst->PROFINET_Mapping_IN.SYSTEM.INPUT = Sim_PROFINET_Mapping_IN[2];
	inst->PROFINET_Mapping_IN.STATE_uID = Sim_PROFINET_Mapping_IN[3];
	inst->PROFINET_Mapping_IN.STATE_mID = Sim_PROFINET_Mapping_IN[4];
	inst->PROFINET_Mapping_IN.MOTION_TRAJECTORY_ID.INPUT[0] = Sim_PROFINET_Mapping_IN[5];
	inst->PROFINET_Mapping_IN.MOTION_TRAJECTORY_ID.INPUT[1] = Sim_PROFINET_Mapping_IN[6];
	inst->PROFINET_Mapping_IN.JOINT_POS[0].INPUT[0] = Sim_PROFINET_Mapping_IN[10];
	inst->PROFINET_Mapping_IN.JOINT_POS[0].INPUT[1] = Sim_PROFINET_Mapping_IN[11];
	inst->PROFINET_Mapping_IN.JOINT_POS[1].INPUT[0] = Sim_PROFINET_Mapping_IN[12];
	inst->PROFINET_Mapping_IN.JOINT_POS[1].INPUT[1] = Sim_PROFINET_Mapping_IN[13];
	inst->PROFINET_Mapping_IN.JOINT_POS[2].INPUT[0] = Sim_PROFINET_Mapping_IN[14];
	inst->PROFINET_Mapping_IN.JOINT_POS[2].INPUT[1] = Sim_PROFINET_Mapping_IN[15];
	inst->PROFINET_Mapping_IN.JOINT_POS[3].INPUT[0] = Sim_PROFINET_Mapping_IN[16];
	inst->PROFINET_Mapping_IN.JOINT_POS[3].INPUT[1] = Sim_PROFINET_Mapping_IN[17];
	inst->PROFINET_Mapping_IN.JOINT_POS[4].INPUT[0] = Sim_PROFINET_Mapping_IN[18];
	inst->PROFINET_Mapping_IN.JOINT_POS[4].INPUT[1] = Sim_PROFINET_Mapping_IN[19];
	inst->PROFINET_Mapping_IN.JOINT_POS[5].INPUT[0] = Sim_PROFINET_Mapping_IN[20];
	inst->PROFINET_Mapping_IN.JOINT_POS[5].INPUT[1] = Sim_PROFINET_Mapping_IN[21];
	inst->PROFINET_Mapping_IN.JOINT_POS[6].INPUT[0] = Sim_PROFINET_Mapping_IN[22];
	inst->PROFINET_Mapping_IN.JOINT_POS[6].INPUT[1] = Sim_PROFINET_Mapping_IN[23];
	inst->PROFINET_Mapping_IN.JOINT_POS_SIGN.INPUT = Sim_PROFINET_Mapping_IN[24];
	
	// Mapping Output Data.
	Sim_PROFINET_Mapping_OUT[1] = inst->PROFINET_Mapping_OUT.STATUS.OUTPUT;
	Sim_PROFINET_Mapping_OUT[3] = inst->PROFINET_Mapping_OUT.SYSTEM.OUTPUT;
	Sim_PROFINET_Mapping_OUT[5] = inst->PROFINET_Mapping_OUT.COMMAND.OUTPUT;
	Sim_PROFINET_Mapping_OUT[6] = inst->PROFINET_Mapping_OUT.COMMAND_mID;
	Sim_PROFINET_Mapping_OUT[7] = inst->PROFINET_Mapping_OUT.COMMAND_uID;
	Sim_PROFINET_Mapping_OUT[10] = inst->PROFINET_Mapping_OUT.TRAJECTORY_SIZE.OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[11] = inst->PROFINET_Mapping_OUT.TRAJECTORY_SIZE.OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[12] = inst->PROFINET_Mapping_OUT.SPEED;
	Sim_PROFINET_Mapping_OUT[13] = inst->PROFINET_Mapping_OUT.ZONE;
	Sim_PROFINET_Mapping_OUT[20] = inst->PROFINET_Mapping_OUT.JOINT_POS[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[21] = inst->PROFINET_Mapping_OUT.JOINT_POS[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[22] = inst->PROFINET_Mapping_OUT.JOINT_POS[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[23] = inst->PROFINET_Mapping_OUT.JOINT_POS[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[24] = inst->PROFINET_Mapping_OUT.JOINT_POS[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[25] = inst->PROFINET_Mapping_OUT.JOINT_POS[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[26] = inst->PROFINET_Mapping_OUT.JOINT_POS[3].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[27] = inst->PROFINET_Mapping_OUT.JOINT_POS[3].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[28] = inst->PROFINET_Mapping_OUT.JOINT_POS[4].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[29] = inst->PROFINET_Mapping_OUT.JOINT_POS[4].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[30] = inst->PROFINET_Mapping_OUT.JOINT_POS[5].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[31] = inst->PROFINET_Mapping_OUT.JOINT_POS[5].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[32] = inst->PROFINET_Mapping_OUT.JOINT_POS[6].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[33] = inst->PROFINET_Mapping_OUT.JOINT_POS[6].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[34] = inst->PROFINET_Mapping_OUT.JOINT_POS_SIGN.OUTPUT;
	Sim_PROFINET_Mapping_OUT[50] = inst->PROFINET_Mapping_OUT.RTOOL_RH.OUTPUT;
	Sim_PROFINET_Mapping_OUT[51] = inst->PROFINET_Mapping_OUT.RTOOL_POS[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[52] = inst->PROFINET_Mapping_OUT.RTOOL_POS[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[53] = inst->PROFINET_Mapping_OUT.RTOOL_POS[0].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[54] = inst->PROFINET_Mapping_OUT.RTOOL_POS[0].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[55] = inst->PROFINET_Mapping_OUT.RTOOL_POS[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[56] = inst->PROFINET_Mapping_OUT.RTOOL_POS[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[57] = inst->PROFINET_Mapping_OUT.RTOOL_POS[1].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[58] = inst->PROFINET_Mapping_OUT.RTOOL_POS[1].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[59] = inst->PROFINET_Mapping_OUT.RTOOL_POS[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[60] = inst->PROFINET_Mapping_OUT.RTOOL_POS[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[61] = inst->PROFINET_Mapping_OUT.RTOOL_POS[2].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[62] = inst->PROFINET_Mapping_OUT.RTOOL_POS[2].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[63] = inst->PROFINET_Mapping_OUT.RTOOL_POS_SIGN.OUTPUT;
	Sim_PROFINET_Mapping_OUT[64] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[65] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[66] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[0].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[67] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[0].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[68] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[69] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[70] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[1].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[71] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[1].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[72] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[73] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[74] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[2].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[75] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[2].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[76] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[3].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[77] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[3].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[78] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[3].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[79] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT[3].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[80] = inst->PROFINET_Mapping_OUT.RTOOL_ROT_QUAT_SIGN.OUTPUT;
	Sim_PROFINET_Mapping_OUT[81] = inst->PROFINET_Mapping_OUT.RTOOL_MASS.OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[82] = inst->PROFINET_Mapping_OUT.RTOOL_MASS.OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[83] = inst->PROFINET_Mapping_OUT.RTOOL_COG[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[84] = inst->PROFINET_Mapping_OUT.RTOOL_COG[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[85] = inst->PROFINET_Mapping_OUT.RTOOL_COG[0].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[86] = inst->PROFINET_Mapping_OUT.RTOOL_COG[0].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[87] = inst->PROFINET_Mapping_OUT.RTOOL_COG[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[88] = inst->PROFINET_Mapping_OUT.RTOOL_COG[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[89] = inst->PROFINET_Mapping_OUT.RTOOL_COG[1].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[90] = inst->PROFINET_Mapping_OUT.RTOOL_COG[1].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[91] = inst->PROFINET_Mapping_OUT.RTOOL_COG[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[92] = inst->PROFINET_Mapping_OUT.RTOOL_COG[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[93] = inst->PROFINET_Mapping_OUT.RTOOL_COG[2].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[94] = inst->PROFINET_Mapping_OUT.RTOOL_COG[2].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[95] = inst->PROFINET_Mapping_OUT.RTOOL_COG_SIGN.OUTPUT;
	Sim_PROFINET_Mapping_OUT[96] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[97] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[98] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[0].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[99] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[0].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[100] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[101] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[102] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[1].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[103] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[1].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[104] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[105] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[106] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[2].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[107] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[2].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[108] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[3].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[109] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[3].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[110] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[3].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[111]  =inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT[3].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[112] = inst->PROFINET_Mapping_OUT.RTOOL_AOM_QUAT_SIGN.OUTPUT;
	Sim_PROFINET_Mapping_OUT[113] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[0].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[114] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[0].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[115] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[0].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[116] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[0].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[117] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[1].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[118] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[1].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[119] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[1].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[120] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[1].OUTPUT[3];
	Sim_PROFINET_Mapping_OUT[121] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[2].OUTPUT[0];
	Sim_PROFINET_Mapping_OUT[122] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[2].OUTPUT[1];
	Sim_PROFINET_Mapping_OUT[123] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[2].OUTPUT[2];
	Sim_PROFINET_Mapping_OUT[124] = inst->PROFINET_Mapping_OUT.RTOOL_MOI[2].OUTPUT[3];
}

